index_lang = {
    'ro':{
        'menu':'menu',
        'our_services_nav':'our services',
        'location_nav':'location',
        'contacts_nav':'contacts',
        'about_us_nav':'about us',
        'our_advantages':'our advantages',
        'advantages_1':'Absolute cleanliness of your car',
        'advantages_2':'We value your time, so you can use electronic queue',
        'advantages_3':'The professional team ready to serve you',
        'advantages_4':'The best care for your car',
        'select_service':'select service',
        'register':'register',
        'location':'location',
        'contacts':'contacts',
        'working_hours':'working hours',
        'mon':'Mon',
        'tue':'Tue',
        'wed':'Wed',
        'thu':'Thu',
        'fri':'Fri',
        'sat':'Sat',
        'sun':'Sun',
        'closed':'Closed',
        'about_us':'about us',
        'about_us_text':'We are a professional detailing and car washing team from Ukraine. We have been working in this field for more than 10 years and coped well with our tasks. But suddenly the war came and we ended up in Romania. Having left our homeland and found ourselves in a new world for us, we could not leave the cause to which we have been devoted for a long time. Therefore, it was decided to start all over again here. We have resumed our business and will be happy to provide decent service to the country that has received us so warmly.',
        'register_to_service':'Register to service',
        'select_date':'Select date',
        'phone_is_wrong':'Phone is wrong, please enter again',
        'enter_your_phone':'Enter Your Phone',
        'next_step':'next step',
        'booking_for_service':'booking for service',
        'your_phone':'Your phone',
        'select_time_for_service':'Select time for service',
        'select_service_option':'Select service option',
        'confirm':'confirm',
        'info_message':'Info message',
        'success_info':'We have accepted your reservation, we will call you back soon to confirm',
        'error_info':'Something wrong, please try again',
        'close':'close',
    },
    'en':{
        'menu':'menu',
        'our_services_nav':'our services',
        'location_nav':'location',
        'contacts_nav':'contacts',
        'about_us_nav':'about us',
        'our_advantages':'our advantages',
        'advantages_1':'Absolute cleanliness of your car',
        'advantages_2':'We value your time, so you can use electronic queue',
        'advantages_3':'The professional team ready to serve you',
        'advantages_4':'The best care for your car',
        'select_service':'select service',
        'register':'register',
        'location':'location',
        'contacts':'contacts',
        'working_hours':'working hours',
        'mon':'Mon',
        'tue':'Tue',
        'wed':'Wed',
        'thu':'Thu',
        'fri':'Fri',
        'sat':'Sat',
        'sun':'Sun',
        'closed':'Closed',
        'about_us':'about us',
        'about_us_text':'We are a professional detailing and car washing team from Ukraine. We have been working in this field for more than 10 years and coped well with our tasks. But suddenly the war came and we ended up in Romania. Having left our homeland and found ourselves in a new world for us, we could not leave the cause to which we have been devoted for a long time. Therefore, it was decided to start all over again here. We have resumed our business and will be happy to provide decent service to the country that has received us so warmly.',
        'register_to_service':'Register to service',
        'select_date':'Select date',
        'phone_is_wrong':'Phone is wrong, please enter again',
        'enter_your_phone':'Enter Your Phone',
        'next_step':'next step',
        'booking_for_service':'booking for service',
        'your_phone':'Your phone',
        'select_time_for_service':'Select time for service',
        'select_service_option':'Select service option',
        'confirm':'confirm',
        'info_message':'Info message',
        'success_info':'We have accepted your reservation, we will call you back soon to confirm',
        'error_info':'Something wrong, please try again',
        'close':'close',
    },
    'ua':{
        'menu':'меню',
        'our_services_nav':'наши услуги',
        'location_nav':'Наш адрес',
        'contacts_nav':'Контакты',
        'about_us_nav':'О нас',
        'our_advantages':'Наши преимущества',
        'advantages_1':'Абсолютная чистостота вашего автомобиля',
        'advantages_2':'Мы ценим ваше время, по этому у нас есть онлайн запись',
        'advantages_3':'Профессиональная команда готова оказать достойный сервис',
        'advantages_4':'Лучшая автохимия для вашего автомобиля',
        'select_service':'Выберите услугу',
        'register':'Запись',
        'location':'Расположение',
        'contacts':'Наши контакты',
        'working_hours':'Рабочие часы',
        'mon':'Пн',
        'tue':'Вт',
        'wed':'Ср',
        'thu':'Чт',
        'fri':'Пт',
        'sat':'Сб',
        'sun':'Вс',
        'closed':'Закрыто',
        'about_us':'О нас',
        'about_us_text':'Мы профессиональная команда дитэйлеров и автомойщиков из Украины. Работали в этой сфере больше 10 лет и хорошо справлялись со свими задачами. Но внезапно пришла война и мы оказались в Румынии. Покинув родину и оказавшись в новом для нас мире, мы не смогли оставить то дело которому преданы уже давно. По этому было принято решение начать все заново здесь. Мы возобновили свое дело и будем рады оказать достойный сервис нашим соотечественникам которые также как и мы оказались в этой стране.',
        'register_to_service':'Запись на услугу',
        'select_date':'Выберите дату',
        'phone_is_wrong':'Неверный номер, введите заново',
        'enter_your_phone':'Введите ваш телефон',
        'next_step':'Далее',
        'booking_for_service':'Запись на услугу:',
        'your_phone':'Ваш телефон',
        'select_time_for_service':'Выберите время записи',
        'select_service_option':'Выберите тип авто',
        'confirm':'подтвердить',
        'info_message':'Информационное сообщение',
        'success_info':'Мы приняли вашу бронь и вскоре перезвоним для подтверждения',
        'error_info':'Что-то пошло не так, попробуйте повторить позже',
        'close':'закрыть',
    },
}